os: linux
dist: xenial
language: c
compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    packages:
    - gcc-5
    - g++-5

before_install:
  - sudo apt-get -qq update
  # - sudo dpkg --add-architecture i386
  # - sudo apt-get update
  # - sudo apt-get install libc6:i386 libstdc++6:i386
  # - sudo apt-get install gcc-multilib libasound2-dev:i386 libgsm1-dev:i386 libjpeg8-dev:i386 liblcms2-dev:i386 libldap2-dev:i386 libmpg123-dev:i386 libopenal-dev:i386 libv4l-dev:i386 libx11-dev:i386 libxinerama-dev:i386 libxml2-dev:i386 zlib1g-dev:i386
  # - sudo apt-get install libcapi20-dev:i386 libcups2:i386 libdbus-1-3:i386 libfontconfig:i386 libfreetype6:i386 libglu1-mesa:i386 libgnutls26:i386 libncurses5:i386 libosmesa6:i386 libsane:i386 libxcomposite1:i386 libxcursor1:i386 libxi6:i386 libxrandr2:i386 libxslt1.1:i386 ocl-icd-libopencl1:i386

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
  - cd ..
  - git clone https://github.com/wine-staging/wine-staging.git
  - cd wine-staging/staging
  - ./patchinstall.py -d ../../wine -a
  - cd ../../wine
  - ./configure --enable-win64
  - make -j$(nproc)
  
after_success:
  - mkdir output
  - mv wine output/
  - mv wine64 output/
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh output/*
