os: linux
dist: xenial
language: c
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    packages:
    - gcc-5
    - g++-5

before_install:
  - sudo apt-get -qq update

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
  - cd ..
  - git clone https://github.com/wine-staging/wine-staging.git
  - cd wine-staging/staging
  - ./patchinstall.py -d ../../wine -a
  - cd ../../wine
  - ./configure
  - make
  - ls build
  

